### ISSUE TITLE
Finish implementing cache handlers

### ISSUE THREAD

**Issue by seliopou** [inhabitedtype/ocaml-webmachine#14]
Time parsing and comparison have not yet been implemented, mostly due to hesitance in adding [calendarlib](http://calendar.forge.ocamlcore.org/) as a dependency. It may be worthwhile considering [ptime](http://erratique.ch/software/ptime) for this use case as well.

The decision nodes in question are `v3h11`, `v3h12`, and `v3l13`.

**Comment by tmcgilchrist** [comment]
I've done h11 and h12 [here](https://github.com/inhabitedtype/ocaml-webmachine/commit/46328b9fb33425c34d94d86163f0fdc2d3dab1e4) but using calendarlib rather than ptime.  What were your concerns about calendarlib? I settled for it cause it had the closest function to what I'd use in Haskell `of_string : string -> string -> Time.t` thought ideally it'd be an option of time rather than exceptions.

**Comment by seliopou** [comment]
This was done a while ago, closing.
